### ISSUE TITLE
Isi Lembar Pernyataan

### ISSUE THREAD

**Issue by aswinte** [Elektro-Unsoed/podoterus#2]
Perlu mencantumkan judul naskah dalam lembar pernyataan
Kalimat: 
"Dengan ini saya menyatakan bahwa dalam Laporan Tugas Akhir/Laporan
Kerja Praktik ini tidak terdapat karya yang pernah diajukan untuk memperoleh
gelar kesarjanaaan di suatu Perguruan Tinggi, dan sepanjang pengetahuan saya
juga tidak terdapat karya atau pendapat yang pernah ditulis atau diterbitkan oleh
orang lain, kecuali yang secara tertulis diacu dalam naskah ini dan disebutkan
dalam daftar pustaka."

menjadi
"Dengan ini saya menyatakan bahwa dalam Laporan Tugas Akhir/Laporan
Kerja Praktik **dengan judul [tuliskan judul di sini]** ini tidak terdapat karya yang pernah diajukan untuk memperoleh
gelar kesarjanaaan di suatu Perguruan Tinggi, dan sepanjang pengetahuan saya
juga tidak terdapat karya atau pendapat yang pernah ditulis atau diterbitkan oleh
orang lain, kecuali yang secara tertulis diacu dalam naskah ini dan disebutkan
dalam daftar pustaka."

**Comment by arifadli** [comment]
Ok pak, siap dikerjakan

**Comment by mulkiiz** [comment]
Format tulisan judulnya ditentukan ga? Misal, mengikuti paragraf saja (huruf kecil semua), dianggap terpisah dengan paragraf sehingga menulisnya dengan style Title?

**Comment by aswinte** [comment]
Done, judul bold dan italic
